### ISSUE TITLE
implementing the style guide

### ISSUE THREAD

**Issue by emilyriehl** [emilyriehl/yoneda#14]
Now that we have a style guide, we should update the library to implement it. I've just experimented with fixing the formatting in "common" and "paths" (without yet fixing the naming of the terms) and I have a few questions I'd like to discuss before making similar edits elsewhere.

**Comment by emilyriehl** [comment]
We haven't explicitly discussed how to format proofs by path induction. Note the syntax for the five arguments that idJ takes is a bit different: they are to be separated by commas in a big pair of parentheses.

Here's is how I've formatted them in one instance. Note a separate issue that came up here is that the type of the declared term is too wide for a single line. In the case of too long identity types, I've been using a line break after the = and indenting so that the two terms being identified start at the same place.

```rzk
#def assoc-concat
  (p : w = x)         -- A path from w to x in A.
  (q : x = y)         -- A path from x to y in A.
  (r : y = z)         -- A path from y to z in A.
  : concat A w x z p (concat A x y z q r) =
    concat A w y z (concat A w x y p q) r
  :=
    idJ(
      A,
      y,
      \ z' r' ->
        concat A w x z' p (concat A x y z' q r') =
        concat A w y z' (concat A w x y p q) r',
      refl,
      z,
      r)
```

**Comment by emilyriehl** [comment]
Sometimes the strategy defined above to break a type declaration of the form ```rzk x = y``` into two lines is still too wide. Here's a particularly rough example. I dealt with the width by giving each argument of triple-concat on its own line, formatted like we'd do in a proof, but should I have done the same for ap? To me, that would have made the statement here harder to read.

```rzk
#def ap-triple-concat
  (A B : U)
  (w x y z : A)
  (f : A -> B)
  (p : w = x)
  (q : x = y)
  (r : y = z)
  : ap A B w z f (triple-concat A w x y z p q r) =
    triple-concat
      B
      ( f w)
      ( f x)
      ( f y)
      ( f z)
      ( ap A B w x f p)
      ( ap A B x y f q)
      ( ap A B y z f r)
  :=
    idJ(
      A,
      y,
      \ z' r' ->
        ap A B w z' f (triple-concat A w x y z' p q r') =
        triple-concat
          B
          ( f w)
          ( f x)
          ( f y)
          ( f z')
          ( ap A B w x f p)
          ( ap A B x y f q)
          ( ap A B y z' f r'),
      ap-concat A B w x y f p q,
      z,
      r)
```

**Comment by emilyriehl** [comment]
In my view all rules are meant to be broken sometimes. Here is an example where I deviated from the style guide's insistence on one argument per line (when everything doesn't fit on a single line). Do you agree?

```rzk
#def 12ary-concat
  (a0 a1 a2 a3 a4 a5 a6 a7 a8 a9 a10 a11 a12 : A)
  (p1 : a0 = a1)
  (p2 : a1 = a2)
  (p3 : a2 = a3)
  (p4 : a3 = a4)
  (p5 : a4 = a5)
  (p6 : a5 = a6)
  (p7 : a6 = a7)
  (p8 : a7 = a8)
  (p9 : a8 = a9)
  (p10 : a9 = a10)
  (p11 : a10 = a11)
  (p12 : a11 = a12)
  : a0 = a12
  :=
    quintuple-concat a0 a1 a2 a3 a4 a12 p1 p2 p3 p4
      (quintuple-concat a4 a5 a6 a7 a8 a12 p5 p6 p7 p8
        (quadruple-concat a8 a9 a10 a11 a12 p9 p10 p11 p12))

-- Same as above but with alternating arguments
#def 12ary-concat-alternating
  (a0 a1 : A)
  (p1 : a0 = a1)
  (a2 : A)
  (p2 : a1 = a2)
  (a3 : A)
  (p3 : a2 = a3)
  (a4 : A)
  (p4 : a3 = a4)
  (a5 : A)
  (p5 : a4 = a5)
  (a6 : A)
  (p6 : a5 = a6)
  (a7 : A)
  (p7 : a6 = a7)
  (a8 : A)
  (p8 : a7 = a8)
  (a9 : A)
  (p9 : a8 = a9)
  (a10 : A)
  (p10 : a9 = a10)
  (a11 : A)
  (p11 : a10 = a11)
  (a12 : A)
  (p12 : a11 = a12)
  : a0 = a12
  :=
    12ary-concat a0 a1 a2 a3 a4 a5 a6 a7 a8 a9 a10 a11 a12
      p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 p12
```

**Comment by emilyriehl** [comment]
It occurs to me that we might want to have an official accepted style that it's okay to write the name of a function, start a new line, indent once, and list all its arguments, provided all of the arguments can be listed on a single line. Here's an example from the discrete types file that attempts to follow the official convention but looks a little silly.

```rzk
#def square-Sigma-over-Prod
  (extext : ExtExt)
  (A : U)
  (Aisdiscrete : is-discrete A)
  (x y z w : A)
  (f : hom A x y)
  (g : hom A z w)
  ((p, (q, τ)) : (∑(p : x = z), (∑(q : y = w),
                  (prod-transport A A (\a b -> hom A a b) x z y w p q f = g))))
  : (∑(h : hom A x z),
      (∑(k : hom A y w),
        (<{(t, s) : 2 * 2 | Δ¹×Δ¹ (t, s)} -> A
            [((t === 0_2) /\  Δ¹ s) |-> f s,
						((t === 1_2) /\  Δ¹ s) |-> g s,
						(Δ¹ t /\  (s === 0_2)) |-> h t,
						(Δ¹ t /\  (s === 1_2)) |-> k t ]>)))
  :=
    ( arr-eq A x z p,
      ( arr-eq A y w q,
        fibered-map-square-Sigma-over-Prod
          extext
          A
          Aisdiscrete
          x
          y
          z
          w
          f
          p
          q
          g
          τ))
```

**Comment by fredrik-bakke** [comment]
I agree with the last suggestion. This is something I/we do in `agda-unimath` as well, although it is not a documented convention.

**Comment by fredrik-bakke** [comment]
> We haven't explicitly discussed how to format proofs by path induction. Note the syntax for the five arguments that idJ takes is a bit different: they are to be separated by commas in a big pair of parentheses.
> 
> Here's is how I've formatted them in one instance. Note a separate issue that came up here is that the type of the declared term is too wide for a single line. In the case of too long identity types, I've been using a line break after the = and indenting so that the two terms being identified start at the same place.
> 
> ```
> #def assoc-concat
>   (p : w = x)         -- A path from w to x in A.
>   (q : x = y)         -- A path from x to y in A.
>   (r : y = z)         -- A path from y to z in A.
>   : concat A w x z p (concat A x y z q r) =
>     concat A w y z (concat A w x y p q) r
>   :=
>     idJ(
>       A,
>       y,
>       \ z' r' ->
>         concat A w x z' p (concat A x y z' q r') =
>         concat A w y z' (concat A w x y p q) r',
>       refl,
>       z,
>       r)
> ```

To be honest, I find this piece of `rzk` syntax a bit odd. It makes the built-in functions look very different from user-defined functions. Would it be possible to change this syntax to look like curried functions, or what is the reasoning for having it like this, @fizruk?

**Comment by fredrik-bakke** [comment]
With the current syntax, I think the following formatting conforms better with the other conventions:

```rzk
idJ
( A ,
  y ,
  \ z' r' ->
    concat A w x z' p (concat A x y z' q r') =
    concat A w y z' (concat A w x y p q) r' ,
    refl ,
  z ,
  r)
```

Also, your choice of line-breaking after the equality symbol is good. Notice how this is consistent with other "binary operators" like `_->_` and `_,_`. This should be the convention for every binary operator.

**Comment by fredrik-bakke** [comment]
> Sometimes the strategy defined above to break a type declaration of the form `rzk x = y` into two lines is still too wide. Here's a particularly rough example. I dealt with the width by giving each argument of triple-concat on its own line, formatted like we'd do in a proof, but should I have done the same for ap? To me, that would have made the statement here harder to read.
> 
> ```
> #def ap-triple-concat
>   (A B : U)
>   (w x y z : A)
>   (f : A -> B)
>   (p : w = x)
>   (q : x = y)
>   (r : y = z)
>   : ap A B w z f (triple-concat A w x y z p q r) =
>     triple-concat
>       B
>       ( f w)
>       ( f x)
>       ( f y)
>       ( f z)
>       ( ap A B w x f p)
>       ( ap A B x y f q)
>       ( ap A B y z f r)
>   :=
>     idJ(
>       A,
>       y,
>       \ z' r' ->
>         ap A B w z' f (triple-concat A w x y z' p q r') =
>         triple-concat
>           B
>           ( f w)
>           ( f x)
>           ( f y)
>           ( f z')
>           ( ap A B w x f p)
>           ( ap A B x y f q)
>           ( ap A B y z' f r'),
>       ap-concat A B w x y f p q,
>       z,
>       r)
> ```

Here, I think it would be most natural to group the function arguments by purpose. For instance, I would probably write

```rzk
triple-concat
  ( B)
  ( f w) (f x) (f y) (f z)
  ( ap A B w x f p)
  ( ap A B x y f q)
  ( ap A B y z f r)
```

Also, to make the larger expression more readable, a good convention is to parenthesize the arguments of binary operators when one of them spans multiple lines. I.e.

```rzk
( ap A B w z f (triple-concat A w x y z p q r)) =
( triple-concat
  ( B)
  ( f w) (f x) (f y) (f z)
  ( ap A B w x f p)
  ( ap A B x y f q)
  ( ap A B y z f r))
```

**Comment by fredrik-bakke** [comment]
Sorry, I would have elaborated on some of this in the style guide if I had had more time.

**Comment by fizruk** [comment]
> To be honest, I find this piece of `rzk` syntax a bit odd. It makes the built-in functions look very different from user-defined functions. Would it be possible to change this syntax to look like curried functions, or what is the reasoning for having it like this, @fizruk?

The builtins have fixed arities, so that it is easier to implement computation and typechecking (all arguments are in place). However, I think I can automatically convert user-friendly syntax into implemenation-friendly one. I will try to make the change with the next release, making current syntax deprecated.

That said, a similar issue arises in other places:

1. Extension types `A [ phi_1 |-> a_1, ..., phi_n |-> a_n ]`
2. Tope disjunction elimination `recOR( phi_1 |-> a_1, ..., phi_n |-> a_n )`

So, we need a convention for lists (of arguments or mappings).

**Comment by emilyriehl** [comment]
@fizruk you mean to call the path-induction function in the example you just showed, right?

I don't have strong feelings about the syntax of idJ (I am pretty happy with the syntax for extension types and tope disjunction, which I find easy to use) but note we now have a similar "based" version of path induction defined to be usable in a more general context (of a family equivalent to but not definitionally equal to) the identity type family. From the fibers file:

```rzk
#section fundamental-thm-id-types

#variable A : U
#variable a : A
#variable B : A -> U
#variable f : (x : A) -> (a = x) -> B x

-- This allows us to apply "based path induction"
-- to a family satisfying the fundamental theorem.
-- Please suggest a better name.
#def ind-based-path
  (familyequiv : (z : A) -> (is-equiv (a = z) (B z) (f z)))
  (P : (z : A) -> B z -> U)
  (p0 : P a (f a refl))
  (x : A)
  (p : B x)
  : P x p
  :=
    (ind-sing
      ( ∑(x : A), B x)
      ( a, f a refl)
      ( \ (x', p') -> P x' p')
      ( contr-implies-singleton-induction-pointed
        ( ∑(x : A), B x)
        ( fund-id-fam-of-eqs-implies-sum-over-codomain-contr familyequiv)
        ( \ (x', p') -> P x' p'))) p0 (x, p)
```

**Comment by fizruk** [comment]
> @fizruk you mean to call the `path-induction` function in the example you just showed, right?

Yes, that was a typo, fixed now!

**Comment by jonweinb** [comment]
Sorry to be late and potentially oblivious to well-established conventions: what is exactly the purpose for extra space after an opening bracket?

E.g.
```
fibered-map-square-Sigma-over-Prod
  ( extext)
  ( A) (Aisdiscrete)
  ( x) (y) (z) (w)
  ( f) (p) (q) (g) (τ)
```
vs
```
fibered-map-square-Sigma-over-Prod
  (extext)
  (A) (Aisdiscrete)
  (x) (y) (z) (w)
  (f) (p) (q) (g) (τ)
```

**Comment by fizruk** [comment]
> Sorry to be late and potentially oblivious to well-established conventions: what is exactly the purpose for extra space after an opening bracket?

See discussion here: https://github.com/emilyriehl/yoneda/pull/12#discussion_r1247956329

**Comment by fredrik-bakke** [comment]
Hi Jonathan! I'll quote my answer to this from elsewhere (in the context of `(` vs. `)`):
> This is the Lisp-like style convention of agda-unimath. The space directly after `(` has a very clear purpose (to align code with indentation levels and make the tree structure of the construction more clear).
This aligns with the following design principle:

> Sorry to be late and potentially oblivious to well-established conventions: what is exactly the purpose for extra space after an opening bracket?
> 
> E.g.
> 
> ```
> fibered-map-square-Sigma-over-Prod
>   ( extext)
>   ( A) (Aisdiscrete)
>   ( x) (y) (z) (w)
>   ( f) (p) (q) (g) (τ)
> ```
> 
> vs
> 
> ```
> fibered-map-square-Sigma-over-Prod
>   (extext)
>   (A) (Aisdiscrete)
>   (x) (y) (z) (w)
>   (f) (p) (q) (g) (τ)
> ```

For context, let me also quote the style guide:

> In Rzk, every
> construction is structured like a tree, where each operation can be seen as a
> branching point. We use indentation levels and parentheses to highlight this
> structure, which makes the code feel more organized and understandable. For
> example, when a definition part extends beyond a line, we introduce line breaks
> at the earliest branching point, clearly displaying the tree structure of the
> definition. This allows the reader to follow the branches of the tree, and to
> visually grasp the scope of each operation and argument. Consider the following
> example about Segal types:
> 
> ```rzk
> #def is-segal-is-local-horn-inclusion
>   ( A : U)
>   ( is-local-horn-inclusion-A : is-local-horn-inclusion A)
>   : isSegal A
>   :=
>     \ x y z f g ->
>     projection-equiv-contractible-fibers
>       ( < {t : 2 * 2 | Λ t} -> A >)
>       ( \ k ->
>         Σ ( h : hom A (k (0_2 , 0_2)) (k (1_2 , 1_2))) ,
>           ( hom2 A
>             ( k (0_2 , 0_2)) (k (1_2 , 0_2)) (k (1_2 , 1_2))
>             ( \ t -> k (t , 0_2))
>             ( \ t -> k (1_2 , t))
>             ( h)))
>       ( second
>         ( comp-equiv
>           ( Σ ( k : < {t : 2 * 2 | Λ t} -> A >) ,
>             Σ ( h : hom A (k (0_2 , 0_2)) (k (1_2 , 1_2))) ,
>               ( hom2 A
>                 ( k (0_2 , 0_2)) (k (1_2 , 0_2)) (k (1_2 , 1_2))
>                 ( \ t -> k (t , 0_2))
>                 ( \ t -> k (1_2 , t))
>                 ( h)))
>           ( < {t : 2 * 2 | Δ² t} -> A >)
>           ( < {t : 2 * 2 | Λ t} -> A >)
>           ( inv-equiv
>             ( < {t : 2 * 2 | Δ² t} -> A >)
>             ( Σ ( k : < {t : 2 * 2 | Λ t} -> A >) ,
>               Σ ( h : hom A (k (0_2 , 0_2)) (k (1_2 , 1_2))) ,
>                 ( hom2 A
>                   ( k (0_2 , 0_2)) (k (1_2 , 0_2)) (k (1_2 , 1_2))
>                   ( \ t -> k (t , 0_2))
>                   ( \ t -> k (1_2 , t))
>                   ( h)))
>             ( equiv-horn-restriction A))
>           ( horn-restriction A , is-local-horn-inclusion-A)))
>       ( horn A x y z f g)
> ```
> 
> The root here is the function `projection-equiv-contractible-fibers`. It takes
> four arguments, each starting on a fresh line and is indented an extra level
> from the root. The first argument fits neatly on one line, but the second one is
> too large. In these cases, we add a line break right after the `->`-symbol
> following the lambda-abstraction, which is the earliest branching point in this
> case. The next node is again `Σ`, with two arguments. The first one fits on a
> line, but the second does not, so we add a line break between them. This process
> is continued until the definition is complete.
> 
> Note also that we use parentheses to mark the branches. The extra space after
> the opening parentheses marking a branch is there to visually emphasize the tree
> structure of the definition, and synergizes with our convention to have
> two-space indentation level increases.
>

**Comment by fizruk** [comment]
> That said, a similar issue arises in other places:
>
> 1. Extension types `A [ phi_1 |-> a_1, ..., phi_n |-> a_n ]`
> 2. Tope disjunction elimination `recOR( phi_1 |-> a_1, ..., phi_n |-> a_n )`
>
> So, we need a convention for lists (of arguments or mappings).

Actually, we can have the following changes to syntax:

1. Use a keyword (e.g. `extends`) and list mappings with an indentation:

   ```rzk
   (t : 2) → A extends
     φ₁ ↦ a₁
     φ₂ ↦ a₂
     ...
     φₙ ↦ aₙ
   ```

   For example,

   ```rzk
   #define hom2
   ( A : U)
     ( x y z : A)
     ( f : hom A x y)
     ( g : hom A y z)
     ( h : hom A x z)
     : U
     := { (t1, t2) : Δ² } -> A extends   -- in A where
       t2 ≡ 0_2 ↦ f t1  -- * the top edge is exactly f,
       t1 ≡ 1_2 ↦ g t2  -- * the right edge is exactly g, and
       t2 ≡ t1  ↦ h t2  -- * the diagonal is exactly h
   ```

   Note that such indentation can always be replaced with braces and semicolons:

   ```rzk
   #define hom2
     ...
     := { (t1, t2) : Δ² } -> A extends { t2 ≡ 0_2 ↦ f t1 ; t1 ≡ 1_2 ↦ g t2 ; t2 ≡ t1 ↦ h t2 }
   ```

2. Similarly, we can replace `recBOT` and `recOR` with something like a
   `case`-expression
   (I'm using `when` here to preserve `case` for inductive types later,
   but any other keyword can be used):

   ```rzk
   when
    φ₁ ↦ a₁
    ...
    φₙ ↦ aₙ
   ```

   For example:

   ```rzk
   #define unfolding-square
     ( A : U)
     ( triangle : Δ² → A)
     : Δ¹×Δ¹ → A
     := λ (t, s) → when
       t ≤ s   ↦ triangle (s , t)
       s <= t  ↦ triangle (t , s)
   ```

   Again, you would be able to write a one-liner with braces and semicolons:

   ```rzk
   ... when { t ≤ s ↦ triangle (s , t) ; s <= t ↦ triangle (t , s) }
   ```

   Note that `recBOT` then can be represented with a vacuous `when`:

   ```rzk
   #define example : {t : 2 | ⊥} → U
     := λ t → when {}
   ```

What do you think?

**Comment by jonweinb** [comment]
I like that suggestion, it seems easy to remember and to use. Is there an easy way to have both this and the previous syntax enabled at the same time?

**Comment by emilyriehl** [comment]
I just pushed a quick and dirty implementation of the style guide throughtout the hott directory. This involved a lot of renaming so please pull right away.

I tried to implement the formatting as best I could. If you notice persistent errors, please let me know. It's likely the result of something I haven't internalized.

I tried to rename the most important functions to conform to the style guide but I let myself keep old names of stuff that didn't feel so important. Please feel free to improve these names/capitalizations. And if you notice that something I changed is still incorrectly named, please let me know.

I reckon it shouldn't be so hard to do the same sort of conversion for the simplicial hott files (since they're much shorter). @jonweinb mentioned he'd take the first pass at that, so I'll stay out of the repository for a couple days now.

**Comment by fredrik-bakke** [comment]
Nice! I've made a draft pull request implementing some conventions, but it is very much a work in progress. I will finish it tomorrow most likely. I think these conventions are best learned by example, so I hope this can assist you in addition to implementing some more of the style guide.

A couple of notable things I've noticed so far that I can mention with regard to your recent commit are the following:

- When `idJ` or similar functions spans multiple lines, the opening parenthesis should be placed on a new line.
- When the argument list of a function spans multiple lines, every argument should be parenthesized. E.g. the following
  ```rzk
  idJ (
    A ,
    x ,
    \ y' q' ->
      ( transport A (\ z -> (a = z)) x y' q' p) = (concat A a x y' p q') ,
    refl,
    y ,
    q)
  ```
  should be instead
    ```rzk
    idJ
      ( ( A) ,
        ( y) ,
        ( \ z' r' ->
          concat A w y z' (concat A w x y p q) r' =
          concat A w x z' p (concat A x y z' q r')) ,
        ( refl),
        ( z) ,
        ( r))
  ```
  Note that it would be less awkward with the previously suggested `path-induction` definition:
  ```rzk
  path-induction
    ( A)
    ( y)
    ( \ z' r' ->
      concat A w y z' (concat A w x y p q) r' =
      concat A w x z' p (concat A x y z' q r'))
    ( refl)
    ( z)
    ( r)
  ```
- When code is written in prose or comments, I think it is good practice to encase it in backticks (`) so that it displays better.
- When math is written in prose or comments, I think it is good practice to encase it in dollar signs ($), so that it is more easily distinguishable from just text, and also it looks better.

**Comment by fredrik-bakke** [comment]
Since I mentioned the comma separator: there is an exception to the above-stated rule, and that is in the notation for Sigma-type formation. I don't really understand why there is a comma in that notation. Is there a specific reason for this, @fizruk?

**Comment by fredrik-bakke** [comment]
I should also mention that I do have some autoformatting code used in the agda-unimath repo that I think could be helpful in this project as well. These would remove the need to keep track of every minor convention, in addition to continuously enforcing them. However, I would like to fix up that code a bit before it is ported, and I likely won't have time for that before late August at the earliest. In the meantime, I wouldn't worry too much about the most minor rules (like spaces before commas, spaces after lambdas, or Sigmas instead of summation symbols).

**Comment by fizruk** [comment]
> Since I mentioned the comma separator: there is an exception to the above-stated rule, and that is in the notation for Sigma-type formation. I don't really understand why there is a comma in that notation. Is there a specific reason for this, @fizruk?

I think this syntax was inspired by Coq's Sigma types. One benefit of this is that you don't have to use parenthesis around the type of the second component, so nested Sigma types don't accumulate tons of extra parentheses.

**Comment by fredrik-bakke** [comment]
Ah, I see. I didn't consider this as with our current style guide we want to accumulate the extra parentheses.
I assume the following functionality isn't in place, but if the Sigma was defined to bind looser than function application, it would be possible to write Sigmas without parentheses around the second argument _and_ without the comma, no?

**Comment by fizruk** [comment]
Simply removing the comma leads to bad syntax, I think:

```
Σ (a : A), B a   -- current syntax
Σ (a : A) B a    -- syntax without comma
                 -- (confusing if B and a are separate arguments to Σ)
Σ (a : A) (B a)  -- syntax without comma, but with parentheses
```

Also note that it is possible to generalise `Σ` to accept arbitrary parameters like in `#define`:

```
Σ (a : A), ∑ (b : B), C a b   -- current syntax
Σ (a : A) (b : B), C a b      -- generalised syntax, comma separates the last (unnamed) component
Σ (a : A) (b : B) (C a b)     -- generalised syntax without commas
```

**Comment by fredrik-bakke** [comment]
Thanks, I see why you would want the comma now. Also, the generalized syntax is neat! I assume it would also be possible to have `B` be a dependent type over `A` in your example?

**Comment by fizruk** [comment]
Yes, `B` may depend on `A` in that example.

**Comment by fredrik-bakke** [comment]
If the generalized Sigma notation is implemented, I think the pairing operator `_,_` (i.e. term introduction for Sigma types) should be redefined to be associative to the left for consistency. Or honestly, I think it should be left associative regardless.

**Comment by fredrik-bakke** [comment]
I also find it a bit odd that commas bind looser than `#def`.

**Comment by fizruk** [comment]
> I also find it a bit odd that commas bind looser than `#def`.

Can you provide an example? I'm not sure this is the case.

**Comment by fredrik-bakke** [comment]
Maybe I'm using the wrong words, but, for instance, I find it unintuitive that the following definition does not type check without the outer parentheses:

```rzk
#def sigma-square-to-sigma-triangle-retraction
  ( A : U)
  ( x y : A)
  ( f : hom A x y)
  ( (g , σ) :
    Σ (g : hom A x y) ,
      ( { (t , s) : 2 * 2 | Δ¹×Δ¹ (t , s)} -> A
        [ ((t === 0_2) /\ Δ¹ s) |-> f s ,
          ((t === 1_2) /\ Δ¹ s) |-> g s ,
          (Δ¹ t /\ (s === 0_2)) |-> x ,
          (Δ¹ t /\ (s === 1_2)) |-> y ]))
  : Σ (d : hom A x y) , hom2 A x y y f (id-arr A y) d
  := ((\ t -> σ (t , t)) , (\ (t , s) -> σ (s , t)))
```
I.e. when writing
```rzk
  := (\ t -> σ (t , t)) , (\ (t , s) -> σ (s , t))
```

**Comment by fizruk** [comment]
I see, that is because syntax for pairs is `(t1 , t2)`, not `t1 , t2`. I see that comma (`,`) as an operator (with optional parentheses) is more familiar to you coming from Agda. I do not object to supporting this Agda-like syntax as long as others accept it. That said, this change should only come with the change to syntax in other places where comma (`,`) is used (extension types (`A [ phi |-> a, ..., psi |-> b ] ) and tope disjunction elimination (`recOR( phi |-> a, ..., psi |-> b )`)).

This is perhaps, another argument in support of the suggestion above: https://github.com/emilyriehl/yoneda/issues/14#issuecomment-1618104985

**Comment by emilyriehl** [comment]
This might not be the right place to raise but anyway... @fizruk 

I've been unable to install rzk-0.5.1 using cabal. I tried both "cabal v1-install rzk" and more recently "cabal v2-build rzk" (which I think is the current suggested usage) and in both cases ended up with the same error:

```
Failed to build optparse-generic-1.5.0.
Build log (
/home/eriehl/.cabal/logs/ghc-8.6.5/optparse-generic-1.5.0-9baf10fef47a6f84a4f867847b6a293ac3f1ac7190046c24a5c020f0c72f455e.log
):
Configuring library for optparse-generic-1.5.0..
Preprocessing library for optparse-generic-1.5.0..
Building library for optparse-generic-1.5.0..
[1 of 1] Compiling Options.Generic  ( src/Options/Generic.hs, dist/build/Options/Generic.o )

src/Options/Generic.hs:344:1: error:
    Could not find module ‘Data.Time.Format.ISO8601’
    Use -v to see a list of the files searched for.
    |
344 | import Data.Time.Format.ISO8601 (ISO8601)
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Options/Generic.hs:354:7: error:
    Module ‘Data.Time’ does not export ‘CalendarDiffDays’
    |
354 |     ( CalendarDiffDays
    |       ^^^^^^^^^^^^^^^^

src/Options/Generic.hs:355:7: error:
    Module ‘Data.Time’ does not export ‘CalendarDiffTime’
    |
355 |     , CalendarDiffTime
    |       ^^^^^^^^^^^^^^^^

src/Options/Generic.hs:368:1: error:
    Could not find module ‘Data.Time.Format.ISO8601’
    Use -v to see a list of the files searched for.
    |
368 | import qualified Data.Time.Format.ISO8601     as ISO8601
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build optparse-generic-1.5.0 (which is required by exe:rzk
from rzk-0.5.1). See the build log above for details.
```
I think this is an issue with cabal as opposed to with rzk. I've was able to pull the latest version from the develop branch of the repository and get everything to typecheck that way (once I fixed an incomplete renaming in the Segal types file).

**Comment by fizruk** [comment]
@emilyriehl We have just released an update to the VS Code extension which should be managing the local `rzk` version by getting the latest binaries from GitHub Releases. This will no be the recommended way to install/update `rzk`.

If you remove `rzk` binaries (use `which rzk` to find out where it is located) and update the VS Code extension, it should prompt you to install the most recent release and handle it for you. Please, let me know if it works.

I will be fixing `cabal-install` problems anyway, but installing from sources should not concern you anymore (only the developers of `rzk`).

**Comment by fizruk** [comment]
> This might not be the right place to raise but anyway...

By the way, the right place would probably be this: https://github.com/fizruk/rzk/issues/43

**Comment by emilyriehl** [comment]
So I went and manually deleted the versions of rzk I'd installed. Then I was prompted by vscode to install the most recent release. But now "which rzk" returns nothing and when I try running "stack exec rzk typecheck .." from the command line in vscode nothing happens. Am I now supposed to typecheck another way?

**Comment by fizruk** [comment]
My apologies, I rushed with the recommendation, I forgot that typechecking is not yet done in VS Code.

Please, install with stack again for now. I will notify you when VS Code will be able to manage everything completely.

**Comment by fizruk** [comment]
> I will notify you when VS Code will be able to manage everything completely.

Thanks to @aabounegm, we have now fixed the issue in the following way (tested on macOS and Windows at the moment):

1. VS Code extension will use globally installed `rzk` if it exists (i.e. in `PATH`).
2. Otherwise, VS Code can manage local installations/updates of `rzk`.
3. If you install/update `rzk` via VS Code extension, it will be available in the Terminal inside VS Code. However, it will not be visible globally (e.g. in the iTerm app, outside VS Code).

Hope this will help you be up-to-date with new releases of `rzk` and avoid building manually from sources!

**Comment by fizruk** [comment]
> ... when I try running "stack exec rzk typecheck .." from the command line in vscode nothing happens. Am I now supposed to typecheck another way?

To clarify, with VS Code extension managing `rzk`, you should run the command without `stack exec` (although it would work with Stack too, it is just redundant):

```sh
rzk typecheck src/hott/* src/simplicial-hott/*
```

**Comment by emilyriehl** [comment]
Obviously we haven't perfectly implemented the style guide yet but this discussion seems to have resolved. Should I close this issue or leave it open until we've finished updating formatting/notation? Fine with me either way.

**Comment by fredrik-bakke** [comment]
> Obviously we haven't perfectly implemented the style guide yet but this discussion seems to have resolved. Should I close this issue or leave it open until we've finished updating formatting/notation? Fine with me either way.

I think now is a good time to close this issue.

**Comment by jonweinb** [comment]
Closed as per agreement in discussion; feel free to initiate or request reopening if needed.
