### ISSUE TITLE
Switch away from curly braces for parameters

### ISSUE THREAD

**Issue by fizruk** [emilyriehl/yoneda#31]
I suggest to go the other direction and remove the use of curly braces for parameters.
This way parameters are always in parentheses (including `(t : 2 | Δ¹ t)`), making code more uniform.
The only place where curly braces remain would be indices used for identity types: `=_{...}` and `refl_{...}`.
I have implemented support for parentheses (also supporting patterns in parameters) in the rzk v0.5.3 (latest release), with current syntax also supported.
If there is no objection to move away from curly braces, I will make a corresponding PR.

_Originally posted by @fizruk in https://github.com/emilyriehl/yoneda/pull/28#discussion_r1261340063_

**Comment by emilyriehl** [comment]
No objection. This and the other syntax improvements look great to me.

Let's add this to the style guide when one of us gets a moment. Maybe in a new section called "notation" or similar?
